### ISSUE TITLE
Error in users.test

### ISSUE THREAD

**Issue by aless133** [nosbog/rsschool-nodejs-task-graphql#1]
We subscribe user1 to user2 but after delete check if user2 is subscribed to user1 what never was a true

We have to subscribe user2 to user1 to check relation deletion

https://github.com/nosbog/rsschool-nodejs-task-graphql/blob/db89267fc40eb9266fe47a192083a0bef61fe426/test/routes/users.test.ts#L183-L200

**Comment by nosbog** [comment]
Связи держат зависимые сущности. В subscribedToUserIds хранятся id тех пользователей, которые на него подписаны.
При удаление user1, из user2.subscribedToUserIds должен исчезнуть user1.id.

**Comment by aless133** [comment]
а `post('/:id/subscribeTo'` должен подписывать юзера из урла на юзера из боди или наоборот? :)

**Comment by nosbog** [comment]
1ый вариант

**Comment by aless133** [comment]
Но эти данные должны хранится во втором юзере (из боди) как список подписчиков, а не в первом как список подписок. Верно?

**Comment by nosbog** [comment]
Если ты ориентируешься на описание таски, то оно неактуально. Еще возможны изменения до выдачи 24.01.
[В UserEntity уже отсутствует userSubscribedToIds.](https://github.com/nosbog/rsschool-nodejs-task-graphql/blob/601f06d9fcafc5e6c79f71654d98782ac55770ec/src/utils/DB/entities/DBUsers.ts#L4). Все связи хранятся только в зависимых сущностях.
